Adapt links & remove category event in Events section
ePages-de/byd-api-content pull request #11
Opened 2019-05-20 07:23 UTC by cgebken

2019-05-20 08:09 UTC, cgebken commented
@Raigen Initially, this PR should only fix the links that differ in Beyond. But when having a closer look at the payloads, I figured out that the category event is not available at all for Beyond. Is that correct?

2019-05-20 08:44 UTC, Raigen commented
> [...] I figured out that the category event is not available at all for Beyond. Is that correct?

You are right, beyond does not have any categories from `epages-ui` perspective, only blank pages with product grid elements. We could also trigger the category event on blank pages when a product grid is used, but we do not do this at the moment.

2019-05-20 09:18 UTC, cgebken commented
@Raigen So the PR is okay like this and can be approved? I think it's best to delete the category section for now and readd it once/ if you change the behavior.

2019-05-20 12:17 UTC, Raigen requested changes

2019-05-20 12:17 UTC, Raigen commented on markdown_stoplight/events.md
> +conditionMicrodata: "ConditionNew"
This is wrong in `epages-ui` for beyond, it should be `NewCondition`

2019-05-20 12:17 UTC, Raigen commented on markdown_stoplight/events.md
> +isVisible: true
This is new for both `Beyond` and `Now`

2019-05-20 12:17 UTC, Raigen commented on markdown_stoplight/events.md
> +stockLevelClass: "little"
This one is either `in`, `little` or `out` depending on the stocklevel state of the product.

2019-05-20 12:17 UTC, Raigen commented on markdown_stoplight/events.md
> +stockLevelClass: "little"
But again is only relevant for our theming, apps should not use it but instead use `stockLevelMicrodata` or the different booleans `onStock`, `warnStock` and `outOfStock`.

2019-05-20 12:17 UTC, Raigen commented on markdown_stoplight/events.md
> +variationMaster: null
This is new for both products

2019-05-20 12:17 UTC, Raigen commented on markdown_stoplight/events.md
> +gtin: null
This is new for both projects, and it can be a string with a gtin number (isbn, ian, etc.)

2019-05-20 12:17 UTC, Raigen commented on markdown_stoplight/events.md
> +links: (2) [{…}, {…}]
```suggestion
links: [{…}, {…}]
```

2019-05-20 15:46 UTC, Raigen approved these changes

2019-05-21 07:23 UTC, BirgitBader approved these changes

2019-05-21 07:23 UTC, merged